Blackjack.Web/Controllers/GameController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Blackjack.BusinessLogic.Services.Interfaces;
using Blackjack.ViewModels.GameViews;
using NLog;

namespace Blackjack.Web.Controllers
{
    public class GameController : AsyncController
    {
        private static Logger logger = LogManager.GetCurrentClassLogger();
        private IGameService _gameService;

        public GameController(IGameService gameService) {
            _gameService = gameService;
        }
       
        [HttpGet]
        public async Task<ActionResult> Start()
        { 
            try
            {
                StartGameView game = await _gameService.Start();
                return View(game);
            }
            catch (Exception e)
            {
                logger.Error(e.Message);
                return View("Error");
            }
        }

        [HttpGet]
        public async Task<JsonResult> StartDealers()
        {
            try
            {
                var dealers = await _gameService.StartDealers();
                return Json(dealers.DealersList, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                logger.Error(e.Message);
                return Json(e, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public async Task<JsonResult> StartPlayers()
        {
            try
            {
                var players = await _gameService.StartPlayers();
                return Json(players.PlayersList, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                logger.Error(e.Message);
                return Json(e, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public async Task<ActionResult> Start(StartGameView startGame)
        {
            try
            {
                var gameId = await _gameService.Start(startGame);
                return RedirectToAction("Play", new { id = gameId });
            }
            catch (Exception e)
            {
                logger.Error(e.Message);
                return View("Error");
            }            
        }
        
        [HttpGet]
        public async Task<ActionResult> Play(long id)
        {
            try
            {
                PlayGameView game = await _gameService.Play(id);
                return View(game);
            }
            catch(Exception e)
            {
                logger.Error(e.Message);
                return View("Error");
            }            
        }

        [HttpPost]
        public async Task<ActionResult> Enough(long gameId)
        {
            try
            {
                await _gameService.Enough(gameId);
                return RedirectToAction("Details", new { id = gameId });
            }
            catch (Exception e)
            {
                logger.Error(e.Message);
                return View("Error");
            } 
        }

        [HttpPost]
        public async Task<ActionResult> More(long gameId)
        {
            try
            {
                await _gameService.More(gameId);
                return RedirectToAction("Play", new { id = gameId });
            }
            catch (Exception e)
            {
                logger.Error(e.Message);
                return View("Error");
            }
        }

        [HttpGet]
        public async Task<ActionResult> History()
        {
            try
            {
                var games = await _gameService.History();
                return View(games);
            }
            catch (Exception e)
            {
                logger.Error(e.Message);
                return View("Error");
            }
        }

        [HttpGet]
        public async Task<ActionResult> Details(long id) {
            try
            {
                DetailsGameView game = await _gameService.Details(id);
                return View(game);
            }
            catch (Exception e)
            {
                logger.Error(e.Message);
                return View("Error");
            }
        }
    }
}

Blackjack.Web/Views/Game/Details.cshtml
@model Blackjack.ViewModels.GameViews.DetailsGameView
@using Blackjack.ViewModels.GameViews

@{
    ViewBag.Title = "Game results";
}

<h2>Game results</h2>
<div>
    <hr />
    <table class="table table-bordered">
        <tr>
            <td> @Html.DisplayNameFor(model => model.Name)</td>
            <td>@Html.DisplayFor(model => model.Name)</td>
        </tr>
        <tr>
            <td> @Html.DisplayNameFor(model => model.CreationDate)</td>
            <td>@Html.DisplayFor(model => model.CreationDate)</td>
        </tr>
    </table>
</div>
<div>
    <table class="table table-bordered">
        <tr>
            <td>@Html.DisplayNameFor(model => model.Dealer)</td>
            <td>@Html.DisplayNameFor(model => model.Dealer.Points)</td>
        </tr>
        <tr>
            <td>@Html.DisplayFor(model => model.Dealer.Name)</td>
            <td>@Html.DisplayFor(model => model.Dealer.Points)</td>
        </tr>
    </table>
</div>
<div>
    <table class="table table-bordered">
        <tr>
            <td>Player</td>
            <td>Playres points</td>
            <td>Players result</td>
        </tr>
        @foreach (GamePlayerDetailsGameViewItem gp in Model.Players)
        {
            <tr>
                <td>@gp.Name</td>
                <td>@gp.Points</td>
                <td>@gp.Result</td>
            </tr>
        }
    </table>
</div>
<p>
    @Html.ActionLink("Back to games history", "History")
</p>

Blackjack.Web/Views/Game/History.cshtml
@model Blackjack.ViewModels.GameViews.HistoryGameView

@{
    ViewBag.Title = "Games history";
}

<h2>Games history</h2>
<p>
    @Html.ActionLink("Start new game", "Start")
</p>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                Game
            </th>
            <th>
                Dealer
            </th>
            <th>
                Player
            </th>
            <th>Creation date</th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model.Games)
    {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                @item.DealerName
            </td>
            <td>
                @item.PlayerName
            </td>
            <td>
                @item.CreationDate
            </td>
            <td>
                @Html.ActionLink("Look game's results", "Details", new { id = item.Id })
            </td>
        </tr>
    }
</table>
<br />

Blackjack.Web/Views/Game/Play.cshtml
@model Blackjack.ViewModels.GameViews.PlayGameView
@using Blackjack.ViewModels.GameViews

@{
    ViewBag.Title = "Play";
}

<h2>Play</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

    </dl>
</div>
<div>
    @using (Html.BeginForm("More", "Game", new { gameId = Model.Id }))
    {
        <input type="submit" value="More" class="btn btn-default btn-block" />
    }
    @using (Html.BeginForm("Enough", "Game", new { gameId = Model.Id }))
    {
        <input type="submit" value="Enough" class="btn btn-default btn-block" />
    }
</div>
<div>
    <table class="table table-bordered">
        <tr>
            <td>@Html.DisplayNameFor(model => model.Dealer)</td>
            <td>@Html.DisplayNameFor(model => model.Dealer.Points)</td>
        </tr>
        <tr>
            <td>@Model.Dealer.Name</td>
            <td>@Model.Dealer.Points</td>
        </tr>
    </table>
</div>
<div>
    <table class="table table-bordered">

        <tr>
            <td>Player</td>
            <td>Players points </td>
            <td>Game result</td>
        </tr>
        @foreach (GamePlayerPlayGameViewItem player in Model.Players)
        {
            <tr>
                <td>@player.Name</td>
                <td>@player.Points</td>
                <td>@player.Result</td>
            </tr>
        }
    </table>
</div>
@section Scripts {
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")
    @Scripts.Render("~/bundles/jqueryval")
}

Blackjack.Web/Views/Game/Start.cshtml
@model Blackjack.ViewModels.GameViews.StartGameView

@{
    ViewBag.Title = "Start";
}

<h2>Start new game</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="Dealers" class="control-label col-md-2">Enter dealer</label>
            <div class="col-md-10">
                <input id="Dealers" name="DealerId" class="k-list-scroller" />
            </div>
        </div>

        <div class="form-group">
            <label for="Players" class="control-label col-md-2">Enter player</label>
            <div class="col-md-10">
                <input id="Players" name="PlayerId" class="k-list-scroller" />
            </div>
        </div>

        <div class="form-group">
            <label for="NewPlayerName" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <input id="NewPlayerName" name="NewPlayerName" type="hidden" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BotsNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BotsNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BotsNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Start game" class="btn btn-default" />
            </div>
        </div>
    </div>

}

<div>
    @Html.ActionLink("Back to games history", "History")
</div>

@section Scripts {
    <script src="~/Scripts/Game/templateLoader.js"></script>
    <script>
        templateLoader.loadExtTemplate("Templates/AddNewItemTemplate.tmpl.htm");
    </script>
    <script src="~/Scripts/Game/Start.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
}

Blackjack.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="~/Content/kendo/2014.1.318/kendo.common.min.css" />
    <link rel="stylesheet" href="~/Content/kendo/2014.1.318/kendo.default.min.css" />
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/kendo/2014.1.318/kendo.all.min.js"></script>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Blackjack", "Start", "Game", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Games history", "History", "Game")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>